import ollama
from google import genai
from app.config.api_keys import gemini_api_key

def getResponseFromLLM(system_prompt : str, user_prompt : str, model_temp : float, format : str = "json"):
    """ Returns a response generated by an llm for a given query with some given configs (temp, format...) """
    
    client = genai.Client(api_key=gemini_api_key)
    response_format = "application/json" if format == "json" else "text/plain"

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=user_prompt,
        config=genai.types.GenerateContentConfig(
                system_instruction=system_prompt,
                response_mime_type=response_format,
                temperature= model_temp
            )
        )
    
    return response


def warm_up_embedding_model():
    ollama.embed(model="embeddinggemma", input="warmup")
